### ISSUE TITLE
Give command error

### ISSUE THREAD

**Issue by antbag-dev** [GrosserZak/PortableCrates#1]
[08:12:59] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\item\Item::setCoun
+() must be of the type int, string given, called in phar:///home/container/plugins/PortableCrates.
phar/src/GrosserZak/PortableCrates/Commands/CrateCommand.phponline195"(EXCEPTION)in"pmsrc/src
/pocketmine/item/Item" at line 569

**Comment by GrosserZak** [comment]
Fixed

**Comment by antbag-dev** [comment]
hey same error
