### ISSUE TITLE
Crash error at line 224 on "GrosserZak/PortableCrates/PCManager"

### ISSUE THREAD

**Issue by Bysyy** [GrosserZak/PortableCrates#11]
Hello ! There is an error when I start my server with the plugin : 

ErrorException: "Undefined array key 0" (EXCEPTION) in "plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager" at line 224
--- Stack trace ---
  #0 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager(224): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[21] Undefined array key 0, string[116] phar://C:/Users/mathi/Desktop/serv local 5.0/plugins/PortableCrates.phar/src/Gro, int 224)
  #1 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager(45): GrosserZak\PortableCrates\PCManager->getCrateItemByData(array[6])
  #2 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager(39): GrosserZak\PortableCrates\PCManager->loadCrates()
  #3 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/Main(26): GrosserZak\PortableCrates\PCManager->__construct(object pocketmine\utils\Config#108526)
  #4 pmsrc/src/plugin/PluginBase(118): GrosserZak\PortableCrates\Main->onEnable()
  #5 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #6 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object GrosserZak\PortableCrates\Main#41816)
  #7 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41356)
  #8 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[38] C:\Users\mathi\Desktop\serv local 5.0\, string[46] C:\Users\mathi\Desktop\serv local 5.0\plugins\)
  #9 pmsrc/src/PocketMine(357): pocketmine\server()
  #10 pmsrc(11): require(string[82] phar://C:/Users/mathi/Desktop/serv local 5.0/PocketMine-MP.phar/src/PocketMine.p)
--- End of exception information ---

**Comment by GrosserZak** [comment]
I'll work on this ASAP

**Comment by GrosserZak** [comment]
Fixed.
Check out the version 2.3.1
