### ISSUE TITLE
Suggesstion: pls see description

### ISSUE THREAD

**Issue by reyyan987** [GrosserZak/PortableCrates#4]
Hello, 
Your plugin is great but if you add this feature it will be extra cool.
So the suggestion is that add a key system as tripwire hook so when a player have the key like if uncommon key  the player can click anywhere in any place and hr will get the specific crate in his inventory slot and then he can open the crate

**Comment by GrosserZak** [comment]
I dont think it will be cool. You're just adding an item you have to right click to get a crate that you have to right click again. I think that's better having the crate directly.

If you have any other suggestions it'll be appreciated.
