### ISSUE TITLE
Missing InvMenu

### ISSUE THREAD

**Issue by DimonYoing** [GrosserZak/PortableCrates#6]
not work

**Comment by GrosserZak** [comment]
Error log please

**Comment by DimonYoing** [comment]
![2022_02_16_22 45 04](https://user-images.githubusercontent.com/98219533/154324755-1daaba46-aaa4-458a-9cc5-7dfd59cc33ca.jpg)
![2022_02_16_22 44 58](https://user-images.githubusercontent.com/98219533/154324763-61494404-9d2b-4f60-9f26-4decf12aeaea.jpg)
![2022_02_16_22 44 53](https://user-images.githubusercontent.com/98219533/154324778-f1b3d3e3-16a8-46c2-a47a-70f3e225b0fa.jpg)
![2022_02_16_22 44 48](https://user-images.githubusercontent.com/98219533/154324821-ff320cc9-2ac9-46f6-8db0-bebee2cee666.jpg)

**Comment by GrosserZak** [comment]
You must have InvMenu virion in your server

**Comment by GrosserZak** [comment]
Where did you get that phar from?

**Comment by Sly-Zipy** [comment]
where we can get invMenu?

**Comment by GrosserZak** [comment]
> where we can get invMenu?

github.com/Muqsit/InvMenu

**Comment by GrosserZak** [comment]
This issue was caused by src-namespace-prefix because poggit shading is not working with it yet. Update is now available
