### ISSUE TITLE
Update To Latest InvMenu Plsss

### ISSUE THREAD

**Issue by Frostyyyyz** [GrosserZak/PortableCrates#8]

**Comment by GrosserZak** [comment]
Could you please send the error message (with backtrace) ?

**Comment by Frostyyyyz** [comment]
I deleted the plugin so the server wouldnt crash, um i might have it hold on.

**Comment by Frostyyyyz** [comment]
all you have to do is update the InvMenu lib i think and im finding the crashlog 

#0 plugins/Pockit.phar/src/LemoniqPvP/PocKit/libs/muqsit/invmenu/InvMenuEventHandler(62): LemoniqPvP\PocKit\libs\muqsit\invmenu\session\network\PlayerNetwork->translateContainerOpen(object LemoniqPvP\PocKit\libs\muqsit\invmenu\session\PlayerSession#152443, object pocketmine\network\mcpe\protocol\ContainerOpenPacket#171279)
  #1 pmsrc/src/event/RegisteredListener(60): LemoniqPvP\PocKit\libs\muqsit\invmenu\InvMenuEventHandler->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent#170355)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#170355)
  #3 pmsrc/src/network/mcpe/NetworkSession(436): pocketmine\event\Event->call()
  #4 pmsrc/src/network/mcpe/InventoryManager(310): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\ContainerOpenPacket#171279)
  #5 pmsrc/src/network/mcpe/InventoryManager(225): pocketmine\network\mcpe\InventoryManager->pocketmine\network\mcpe\{closure}()
  #6 pmsrc/src/network/mcpe/InventoryManager(312): pocketmine\network\mcpe\InventoryManager->openWindowDeferred(object Closure#171757)
  #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(582): pocketmine\network\mcpe\InventoryManager->onClientOpenMainInventory()
  #8 pmsrc/vendor/pocketmine/bedrock-protocol/src/InteractPacket(57): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInteract(object pocketmine\network\mcpe\protocol\InteractPacket#171975)
  #9 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\InteractPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#148448)
  #10 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InteractPacket#171975, string[3] !..)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[52] cVdc4.....x...4G.....T.9..:......c.....vK.9.z.......)
  #12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[61] ...b.sg..(...O..R.......D=*..n.......>'.p.&..5w.}..n.....I.qJ)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#34974)
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #16 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1670128461.5041)
  #17 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
  #18 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #19 pmsrc/src/PocketMine(351): pocketmine\server()
  #20 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[04:34:21.513] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[04:34:21.536] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Sun_Dec_4-04.34.21-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[04:34:21.809] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/7924578 or use the ID #7924578.

**Comment by Frostyyyyz** [comment]
Yes ik that says pockit, but its thing plugin aswell, if i delete pockit and it will say portablecrates, then invsee, and playervaults

**Comment by Frostyyyyz** [comment]
![image](https://user-images.githubusercontent.com/119028432/206327843-8c780015-b0e0-4b69-98b3-5f5f680acde9.png)

**Comment by Frostyyyyz** [comment]
![image](https://user-images.githubusercontent.com/119028432/206328089-098992ee-3c56-4063-a970-776d2855cab5.png)

**Comment by GrosserZak** [comment]
Fixed. The  updated version is available on the poggit page
